### ISSUE TITLE
Update the color scheme

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordCamp-Android#14]
We should use WordPress colors:
https://make.wordpress.org/design/handbook/foundations/colors/

**Comment by maxme** [comment]
ping @hugobaeta and @camworld

**Comment by maxme** [comment]
I took some screenshots of the main app screens:
https://cloudup.com/cUv6BUmdEVM

**Comment by samuelsidler** [comment]
Seeing the colors from #18 makes me wonder...

@hugobaeta: Why did you choose yellow for the underlined selected state vs green or another highlight color? And why orange for the bookmark? I see "bookmarks" as similar to "starring" and would want them to be yellow. Or... similar to "hearting" and red, but red is usually used for warnings in WordPress.

**Comment by hugobaeta** [comment]
@samuelsidler 

> Why did you choose yellow for the underlined selected state vs green or another highlight color? 

I experimented a big and thought going with a different accent color than Orange would be a good change. The yellows are still from our Official Color Palettes.

> And why orange for the bookmark?

I was going for a bit more contrast, but I agree, if we go with Yellow, it should be yellow all the way. If we default to Orange, it should be orange all the way.

I'll update the design on #18 to all yellows as accents.

**Comment by maxme** [comment]
Color palette added in f40445a74384ef47e3779a9cea4242d4e388d0c1
