### ISSUE TITLE
Main Navigation enhancements

### ISSUE THREAD

**Issue by hugobaeta** [wordpress-mobile/WordCamp-Android#17]
I would like to propose two things regarding the app navigation:
- **Rename "My WordCamps" to "Attending"** - [Material Design guidelines has clear references to language](http://www.google.com/design/spec/style/writing.html#writing-language) and how an app should address the users. "My..." should not be used. So I'm proposing a more active language and simply change it to "Attending".
- **Removing "Past" WordCamps**. I don't understand the purpose of having them explicitly in the app. They should definitely be searchable, but unless there's a concrete use-case for them, I'd just remove that tab completely to make the app leaner.

Here's a mockup of this:

![navigation-review](https://cloud.githubusercontent.com/assets/1514660/8238448/b2caf462-15ed-11e5-8997-27772cdd113a.png)

Let's hear feedback about this before implementing. 

cc/ @maxme @camworld

**Comment by hugobaeta** [comment]
As a clarification: The "bookmarking" action you can do, to build the "My WordCamps" list in the current build has nothing to do with actually attending WordCamps. It's an app-only thing, a way to "bookmark" or "favorite" WordCamps, the user isn't actually buying a ticket or anything.

Maybe "Bookmarked" or "Favorites" would be more appropriate than "Attending"...   (In response to @markoheijnen [comment](https://github.com/wordpress-mobile/WordCamp-Android/issues/20#issuecomment-113533468))

**Comment by hugobaeta** [comment]
Following up on feedback from @samuelsidler on #18 - here's a review of the proposed chang, using "Favorites" instead:

![navigation-proposal-2](https://cloud.githubusercontent.com/assets/1514660/8258821/08d3e914-16b0-11e5-8899-e26f9ed65f85.png)

**Comment by maxme** [comment]
- [x] Rename "My WordCamps" to "Favorites" 
- [x] Remove "Past" WordCamps
