### ISSUE TITLE
Design Review - "Upcoming" view

### ISSUE THREAD

**Issue by hugobaeta** [wordpress-mobile/WordCamp-Android#18]
The Upcoming view app – that works as the home view for the app – currently presents a few issues that can be improved, specifically to adhere to Material Design guidelines. 

Here's a series of mockups that I'll discuss in this ticket (click the image to see larger):

![upcoming-view](https://cloud.githubusercontent.com/assets/1514660/8237959/ae83321e-15ea-11e5-8a4c-1a68670701ca.png)

The current build (**Upcoming_CB**) doesn't have the [recommended spacing](http://www.google.com/design/spec/layout/metrics-keylines.html) between list items and has what looks to me as a bug (the zoomed in detail - looks like each row has rounded corners and a shadow to them, only visible on the edges of the app).
- **Upcoming_P1** retains the same principles of the current build, but with adjusted metrics and colors. 
- **Upcoming_P2** plays with the idea of removing the circles, since they don't really add anything to the layout (I don't understand their purpose).
- **Upcoming_P3** explores what a more involved layout could look like. It uses Material Design's cards template, and a photo of the WordCamp city to create some interest. This is obviously a significant change in the way the app works, so it serves simply as a conversation starter.

I'm definitely leaning strongly towards **Upcoming_P2**, removing the pointless circles. What do y'all think?

When tickets for specific actions are created, I'll update this one with links to them. This one serves only for discussion, but a quick list of specifics involved in **Upcoming_P2**:
- Increased spacing on list items
- Removal of list item avatar circles
- Removal of "WordCamp" before each city name ("WordCamp Kansas City" becomes "Kansas City")
- (If possible) Change hyphens on date ranges to _en-dashes_ ("Jun 13, 2015 - Jun 16, 2015" becomes "Jun 13, 2015 – Jun 16, 2015") - _en-dashes_ are the correct typographical element to indicate ranges. 

This mockup also includes revised colors, but I'll wait till I've gone through all screens before updating issue #14 (where colors are being discussed).

cc/ @maxme @camworld

**Comment by samuelsidler** [comment]
I really like these designs.

Fwiw, I prefer the list view of Upcoming_P2 because it's much easier to find an upcoming WordCamp with a list than with large cards. I like the design of the cards and it might make sense to use them in the future. Does Material Design allow for toggles to switch between views? That would be one way around this in the future.

**Comment by hugobaeta** [comment]
> Does Material Design allow for toggles to switch between views?

hahaha... "Decisions, not options" IMO. It's such a small app, I don't think we need a view toggle for this.

I agree, let's move with **Upcoming_P2**. Let me just update the screenshot with a couple of things and I'll leave a final comment here with actionable items!

**Comment by maxme** [comment]
> Fwiw, I prefer the list view of Upcoming_P2 because it's much easier to find an upcoming WordCamp with a list than with large cards.

I agree, we could have the card view for "Attending", most users will have a very few cards on this tab.

**Comment by hugobaeta** [comment]
> we could have the card view for "Attending", most users will have a very few cards on this tab.

I thought about that but didn't mention it because I was slightly cautious about having different experiences for what are essentially the same types of lists. But I guess that could work!

**Comment by hugobaeta** [comment]
Here's the latest mockup, going with **Upcoming_P2** approach:

![upcoming_p2](https://cloud.githubusercontent.com/assets/1514660/8254944/39939840-1694-11e5-94c0-00e81c708858.png)

## Actionable Items:
- Increased spacing on list items ([view Two-line list specs](http://www.google.com/design/spec/components/lists.html#lists-specs))
- Removal of list item avatar circles
- Fix issue with list items having a round border and shadow that is visible on the edges (see magnified detail on **Upcoming_CB**, on the right side of the screenshot)
- Change of colors of list item title (HEX#32373C), list item date (HEX#A0A5AA), and bookmark icon (I can make the new icons myself, and add a patch for it)
- (If possible) Change hyphens on date ranges to en-dashes ("Jun 13, 2015 - Jun 16, 2015" becomes "Jun 13, 2015 – Jun 16, 2015") - en-dashes are the correct typographical element to indicate ranges.

**Comment by samuelsidler** [comment]
One more question. :) Why are we using a bookmark icon instead of a star or heart? :)

I'm not sure we use the "bookmark" metaphor anywhere in core. We do have a star, but usually use it for ratings: https://developer.wordpress.org/resource/dashicons/#star-filled

And we have a heart that we use for "favorite" in the plugin directory: https://developer.wordpress.org/resource/dashicons/#heart

If the metaphor here is "bookmark," we should probably consider calling the second tab "bookmarked" or "favorites" or "watching" or something similar. Do we expect people will only use the app / bookmark a WordCamp when they're attending it? Or will they use it to track upcoming WordCamps that they're interested in? Or even to follow along with a WordCamp that has a live stream?

**Comment by hugobaeta** [comment]
> And we have a heart that we use for "favorite" in the plugin directory:

As we discussed on slack, using the heart makes the most sense. I'm using the heart from dashicons for consistency with our iconography language.

Updating mockups with it:

![favorites-hearts](https://cloud.githubusercontent.com/assets/1514660/8258934/c6aec724-16b0-11e5-9c66-32a30d812553.png)

**Comment by maxme** [comment]
- [x] Implement Upcoming_P2
- [x] Change hyphens on date ranges to en-dashes ("Jun 13, 2015 - Jun 16, 2015" becomes "Jun 13, 2015 – Jun 16, 2015") in 80924f9
- [x] Increase spacing on list items 
- [x] Remove of list item avatar circles
- [x] Change of colors of list item title list item date  and bookmark icon 4fb5a0b
- [x] Fix issue with list items having a round border and shadow that is visible on the edges (replace cardview with a linearlayout)
