### ISSUE TITLE
Design Review - "Favorites" View

### ISSUE THREAD

**Issue by hugobaeta** [wordpress-mobile/WordCamp-Android#20]
Following the discussion around #18 (Design enhancements to "Upcoming" view) and #17 (change "My WordCamps" to "Attending, and getting rid of "Past" navigation item), here's a couple of proposals for the "Attending" view:

![attending-view-proposal](https://cloud.githubusercontent.com/assets/1514660/8255342/4053d048-1697-11e5-971a-191536a41196.png)
- **Attending_CB** - Current Build, the same buggy looking rounded corner+shadow exists here, same as on **Upcoming_CB** in #18 
- **Attending_P1** - The actionable items would be in line with #18 - same principles
- **Attending_P2** - since there will always be less items on this list, it might be great to use my proposal for an alternate view of a list, using the cards component, like @maxme suggested.

Thoughts?

**Comment by markoheijnen** [comment]
Personally I would keep my WordCamps because I plan where I'm going but I still need to look if I'm able to go. Having the ability to build that list would be great.

Deleting Past would be a complete miss. New posts could pop up, new photo's, movies, post with all presentations. In the future feedback could be added to. Highlighting that in the app would be great. Like a bubble showing how many new posts/actions happened in the past WordCamps.

**Comment by markoheijnen** [comment]
I do like Attending_P2. Unsure about the total height of the item but definitely makes the list looks nice to watch at.

**Comment by hugobaeta** [comment]
@markoheijnen Your first comment doesn't belong here. Please see the issue that was open to discuss that and the explanations for the change: #17

**Comment by hugobaeta** [comment]
@markoheijnen 

> Unsure about the total height of the item

I used a [cards component from the Material Design guidelines](http://www.google.com/design/spec/components/cards.html). But I'm sure we could reduce the height. i personally like it so you can have a better sense of the photo in there, it keeps a decent ratio.

**Comment by hugobaeta** [comment]
Update Proposals, with "Favorites" (instead of "Attending", per discussion on #17), and heart icon (instead of bookmark, per discussion on #18):

![favorites-view-rev](https://cloud.githubusercontent.com/assets/1514660/8259857/a854e6bc-16b7-11e5-8c9d-97660678ed11.png)

**Comment by maxme** [comment]
Fixed via #17
