### ISSUE TITLE
Appbar Menu colors

### ISSUE THREAD

**Issue by hugobaeta** [wordpress-mobile/WordCamp-Android#21]
The Appbar "more" menu, displayed when the user taps the 3 dots icon on the far left of the App bar, need some love. I would like to suggest to default it to Material Design guidelines:

![appbar-menu-enhancement](https://cloud.githubusercontent.com/assets/1514660/8260271/517da3da-16ba-11e5-97b7-6d2b0a52ed9c.png)

**Comment by maxme** [comment]
fixed in https://github.com/wordpress-mobile/WordCamp-Android/commit/fcfd0652ba8b5d86c6eb081fa440a5a8e168a0ae

![mop](https://cloud.githubusercontent.com/assets/40213/8284575/e8168f10-18fd-11e5-8160-869478fdc984.png)
