### ISSUE TITLE
Design Review - WordCamp "Overview" tab

### ISSUE THREAD

**Issue by hugobaeta** [wordpress-mobile/WordCamp-Android#26]
![wordcamp_overview_proposal](https://cloud.githubusercontent.com/assets/1514660/8296331/43230796-1947-11e5-895a-99dcb19cf018.png)
- **WordCamp_Overview_CB** - The current view. It looks like there's a card in there, but the edges look buggy. The issues to solve here are hierarchy of information.
- **WordCamp_Overview_P1** - This proposal focuses on making the hierarchy better by assuming the card structure, with a primary action per card - _Navigate_ on the Location card, and _Visit Website_ on the about card. I also moved the date down to a card, following @maxme [comment on another ticket](https://github.com/wordpress-mobile/WordCamp-Android/issues/23#issue-90091333), with an idea to add a "Add to Your Calendar" primary action button (not sure if it's doable, but would be cool).
- **WordCamp_Overview_P2** - This other proposal explores the idea of a larger header, where the date would fit as well as a featured image from the event. PRobably too hard to implement for 1.0 cycle, but could be an idea for the future.

Comments? ;)

**Comment by hugobaeta** [comment]
Oh, forgot to mention:
- Removed the refresh button, it should go on the Appbar menu.
- Disregarded the bookmark/favorite icon on the Appbar, wanted to clear up the Appbar a bit. The user can mark and unmark it as favorite on the list view easily. If you think it's absolutely necessary there, we can add it back. But I don't think it's a big deal if it's not there.
- Placed search there for consistency, but that could go away in favor of space if needed. Ideally this search would be contextual, and look for elements from this specific WordCamp.

**Comment by maxme** [comment]
> an idea to add a "Add to Your Calendar" primary action button (not sure if it's doable, but would be cool).

I like it

> Removed the refresh button, it should go on the Appbar menu.

:+1:  removed already

> Placed search there for consistency, but that could go away in favor of space if needed. Ideally this search would be contextual, and look for elements from this specific WordCamp.

LIke filter schedule / speaker lists? We should maybe hide it on the Overview page (and use a nice show/hide animation).

**Comment by hugobaeta** [comment]
> LIke filter schedule / speaker lists? We should maybe hide it on the Overview page (and use a nice show/hide animation).

Yes, if you search within the WordCamp view, you could look for strings within the contents of the WordCamp.

**Comment by maxme** [comment]
> Yes, if you search within the WordCamp view, you could look for strings within the contents of the WordCamp.

What's the WordCamp view? the "Overview" tab? You mean highlight text in the CardViews (Date / Location / About)?

**Comment by maxme** [comment]
- [ ] Search button (new issue to be opened)
- [x] Create 3 Cardviews (date / location / about)
- [x] Create 3 Cardviews (date / location / about)
- [x] Change to a standard Action bar
- [x] Remove the fav button from the action bar
- [x] New `Navigate` flat button
- [x] New `Visit Website` flat button
- [ ] New `Add to my calendar` flat button (new issue to be opened)
- [x] Restyle margins, use default card elevation / corner radius
- [x] Fix scrolling view

**Comment by maxme** [comment]
Fixed https://cloudup.com/cbFzw3q8CP5

**Comment by hugobaeta** [comment]
@maxme 
- careful with the margins, you gave twice as much margin to the card as they should have ;) The padding seems correct, but the margi from the screen edge should be 2dp (instead of the regular 4dp)
-  the separator line between a card content and the buttons should be rgba(50,55,60,0.12)
