### ISSUE TITLE
Design Review - WordCamp "Schedule"

### ISSUE THREAD

**Issue by hugobaeta** [wordpress-mobile/WordCamp-Android#28]
![wordcamp_schedule_p1](https://cloud.githubusercontent.com/assets/1514660/8305228/e1d309ce-19a4-11e5-9de7-41db9ef6ed29.png)

Just one proposal here, to make the list items more standard with the rest of the app.

details:
- The List SubHeaders (gray text with date and time) should, if possible, have the time in Bold, while the rest is standard to Regular
- Is it possible to add the Speaker name next to the room/track? I feel like if I'm doing an overview of the schedule, it helps to quickly see who's talking about what

**Comment by maxme** [comment]
- [x] The List SubHeaders (gray text with date and time) should, if possible, have the time in Bold, while the rest is standard to Regular
- [ ] Is it possible to add the Speaker name next to the room/track? I feel like if I'm doing an overview of the schedule, it helps to quickly see who's talking about what
- [x] Consolidate margins with other list views
- [x] Remove text centering
- [x] Remove italic on subtittle
- [x] Fix date localization

**Comment by maxme** [comment]
It's possible to add speaker name(s) to the room/track, creating a new issue for it see #30
