### ISSUE TITLE
Some views need metrics and keyline improvements

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordCamp-Android#31]
Cool app! I noticed a few views of the app that could use some padding/margin improvements in order to match the material [Metrics & Keylines](http://www.google.com/design/spec/layout/metrics-keylines.html) specs:

The avatars need additional padding, at least 8dp on each side:
![screen shot 2015-06-23 at 9 39 31 am](https://cloud.githubusercontent.com/assets/789137/8310275/11b7155e-198c-11e5-97bd-93a200de472c.png)

There should be at least a 16dp margin for this text block:
![screen shot 2015-06-23 at 9 38 35 am](https://cloud.githubusercontent.com/assets/789137/8310294/29f7039a-198c-11e5-8094-01ed74551ad5.png)

**Comment by maxme** [comment]
Should be fixed via #26

**Comment by maxme** [comment]
Fixed 
https://cloudup.com/czrq8wFqcjR
and
https://cloudup.com/cbFzw3q8CP5
