### ISSUE TITLE
HTML encoding is handled differently between screens

### ISSUE THREAD

**Issue by morganestes** [wordpress-mobile/WordCamp-Android#63]
Ampersands (and possible other chars) display as "&" on the schedule list, but are encoded to "&amp;" in the session detail view.

**Comment by morganestes** [comment]
https://cldup.com/6AULeeFNUg.png

https://cldup.com/KYF6_g-Vvl.png

**Comment by morganestes** [comment]
Also, it's difficult to create new issues on GitHub mobile that aren't a complete mess. :sadpanda:

**Comment by aagam-shah** [comment]
Thanks for reporting @morganestes
